name: "CICD test"
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: Amazon Linux
    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        USER_NAME: ${{ secrets.USER_NAME }}
        HOST_NAME: ${{ secrets.HOST_NAME }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} 'cd the-app &&
        touch /home/ec2-user/test/ok.txt'
