name: Release to Production Environment
on:
  push:
    branches:
      - main

jobs:
  job1:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ssh and deploy
        uses: appleboy/ssh-action@master # １
        with: # ２ アクションの入力パラメータを指定
          host: ${{ secrets.HOST_NAME }} # ホスト名
          username: ${{ secrets.USER_NAME }} # SSH ユーザ名
          key: ${{ secrets.PRIVATE_KEY }} # 秘密鍵の内容
          port: ${{ secrets.SSH_PORT }} # ポート番号
          script: |
            touch /home/ec2-user/test/ok.txt
